### ISSUE TITLE
Question: Recursive Visuals

### ISSUE THREAD

**Issue by borgmanJeremy** [jainpranav1/Nand2Tetris-HDL-Visualizer#5]
Is there any way to have this recursively generate the gates down to just NAND gates? What I mean is if I'm making a Mux that uses an And gate which use a Nand gate (etc), can this visualize it all down to the NAND gates?

**Comment by jainpranav1** [comment]
Hey! Currently the tool does not provide any way to recursively generate the gates down to just NAND gates. Actually, if the tool did, the diagram would actually become extremely cluttered, but would be interesting to see. If you can figure out how to preprocess HDL files such that they only contain Nand gates, then you can use the visualizer to see the design.

**Comment by borgmanJeremy** [comment]
Thanks!
