### ISSUE TITLE
Expected [a-z,A-Z], comment, or whitespace but "}" found.

### ISSUE THREAD

**Issue by docentYT** [jainpranav1/Nand2Tetris-HDL-Visualizer#6]
I'm getting an error:
```
Command 'Visualize HDL File' resulted in an error
Expected [a-z,A-Z], comment, or whitespace but "}" found.
```
when I am trying to visualize the following code:
```hdl
// This file is part of www.nand2tetris.org
// and the book "The Elements of Computing Systems"
// by Nisan and Schocken, MIT Press.
// File name: projects/01/Xor.hdl

/**
 * Exclusive-or gate:
 * out = not (a == b)
 */

CHIP Xor {
    IN a, b;
    OUT out;

    PARTS:
    Not(in=a, out=nota);
    Not(in=b, out=notb);
    And(a=a, b=notb, out=aAndNotB);
    And(a=nota, b=b, out=bAndNotA);
    Or(a=aAndNotB, b=bAndNotA, out=out);
}
```

**Comment by jainpranav1** [comment]
Thanks for trying out the extension! I'll take a look and see what the issue is.

**Comment by jainpranav1** [comment]
It seems to work fine for me.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/64936978/224768059-9371f5fb-8a34-4218-b828-bbc0501e9344.png">

**Comment by jainpranav1** [comment]
The error you are receiving looks like a parsing error. The parser I use is from here: https://www.npmjs.com/package/hdl-parser.

**Comment by docentYT** [comment]
I found what the error is in. I did not have parts defined for the components I was using.
If I remember correctly, it was mentioned in the nand2tetris course that the simulation program has predefined components so that you don't have to manually create all of them. And I rather don't see the point of using them for visualization when a single .hdl file could suffice.

**Comment by jainpranav1** [comment]
Awesome that you figured out the error! The reason the the extension needs to examine the components is to determine what pins are inputs and what pins are outputs to show the visualization correctly.

**Comment by docentYT** [comment]
> needs to examine the components is to determine what pins are inputs and what pins are outputs

It is not necessary to know all the `PARTS` for this. `IN` and `OUT` will be enough.

**Comment by jainpranav1** [comment]
The way the extension works is the following. If the extension observes a component with the same name of a builtin nand2tetris chip, it will first check the directory to see if the user has defined the component. If no file is found, the extension assumes the component is a builtin  nand2tetris chip and uses information from [here ](https://github.com/jainpranav1/Nand2Tetris-HDL-Visualizer/blob/main/bltin_chips.json)to determine the inputs. This mechanism is useful for example if I want to define a custom chip that shares the name of a builtin chip, but has different pins. For example, a custom ALU.

**Comment by jainpranav1** [comment]
In short, if you don't want to define builtin nand2tetris chip yourself, don't include their files in your directory.
