### ISSUE TITLE
Feature request: Display API documentation comment

### ISSUE THREAD

**Issue by docentYT** [jainpranav1/Nand2Tetris-HDL-Visualizer#7]
It would be useful to display the `API documentation comment` under the file name in the chip preview.

`API documentation comment` syntax from the [HDL documentation](https://drive.google.com/file/d/1dPj4XNby9iuAs-47U9k3xtYy9hJ-ET0T/view):
```hdl
/** API documentation comment */
```

**Comment by jainpranav1** [comment]
This is a good idea! I can take a look to see if the parser I am using provides an easy way to get access to the api documentation comment.

**Comment by jainpranav1** [comment]
The parser does not unfortunately access the api documentation comment.
